"""Training utilities for PINN-Phase."""

from .config import (
    GradNormConfig,
    ModelConfig,
    PhysicsConfig,
    build_gradnorm_controller,
    build_residual_blend,
)
from .explicit_mpf_trainer import (
    ExplicitMPFTrainResult,
    ReferenceLeakageError,
    assert_no_reference_leakage,
    build_explicit_mpf_model,
    energy_lh2_density_loss,
    energy_lh2_interface_mask,
    mpf_pairwise_energy_density,
    mpf_residual_loss,
    train_explicit_mpf,
    write_rollout_snapshot,
)
from .baseline import (
    SurrogateTrainingConfig,
    SurrogateTrainingHistory,
    train_autoregressive_surrogate,
)
from .losses import (
    decode_latent_rollout,
    decoded_latent_physics_loss,
    driving_potential,
    driving_shape,
    energy_monotonicity_loss,
    periodic_laplacian_2d,
    projected_scalar_allen_cahn_rhs,
    scalar_allen_cahn_rhs,
    scalar_free_energy,
    scalar_free_energy_3d,
    scalar_pde_residual,
    scalar_pde_residual_loss,
)
from .optimizers import (
    GradNormController,
    OptimizerBundle,
    OptimizerGroup,
    OptimizerOwnershipError,
    build_adam_optimizers,
)
from .modes import ModeLosses, TrainingMode, TrainingModeConfig, compute_mode_losses
from .trainer import TBPTTEpochResult, train_tbptt_epoch
from .pinn import (
    EarlyStopTriggered,
    PINNTrainingConfig,
    PINNTrainingHistory,
    rollout_pinn,
    rollout_pinn_radii,
    train_pinn_physics_only,
)

__all__ = [
    "GradNormConfig",
    "ModelConfig",
    "PhysicsConfig",
    "build_gradnorm_controller",
    "build_residual_blend",
    "ExplicitMPFTrainResult",
    "ReferenceLeakageError",
    "assert_no_reference_leakage",
    "build_explicit_mpf_model",
    "energy_lh2_density_loss",
    "energy_lh2_interface_mask",
    "mpf_pairwise_energy_density",
    "mpf_residual_loss",
    "train_explicit_mpf",
    "write_rollout_snapshot",
    "SurrogateTrainingConfig",
    "SurrogateTrainingHistory",
    "train_autoregressive_surrogate",
    "decode_latent_rollout",
    "decoded_latent_physics_loss",
    "driving_potential",
    "driving_shape",
    "energy_monotonicity_loss",
    "periodic_laplacian_2d",
    "projected_scalar_allen_cahn_rhs",
    "scalar_allen_cahn_rhs",
    "scalar_free_energy",
    "scalar_free_energy_3d",
    "scalar_pde_residual",
    "scalar_pde_residual_loss",
    "GradNormController",
    "OptimizerBundle",
    "OptimizerGroup",
    "OptimizerOwnershipError",
    "build_adam_optimizers",
    "ModeLosses",
    "TrainingMode",
    "TrainingModeConfig",
    "compute_mode_losses",
    "TBPTTEpochResult",
    "train_tbptt_epoch",
    "EarlyStopTriggered",
    "PINNTrainingConfig",
    "PINNTrainingHistory",
    "rollout_pinn",
    "rollout_pinn_radii",
    "train_pinn_physics_only",
]
