"""Reference phase-field physics."""

from .reference_solver import (
    ScalarAllenCahnConfig,
    SimulationResult,
    circular_grain,
    equivalent_radius,
    free_energy,
    load_benchmark_config,
    periodic_laplacian,
    planar_slab,
    scalar_rhs,
    simulate,
)
from .multiphase_solver import (
    MultiphasePFConfig,
    MultiphaseResult,
    initial_multiphase_condition,
    load_multiphase_config,
    multiphase_free_energy,
    multiphase_rhs,
    multigrain,
    simulate_multiphase,
    two_grain_circular,
)
from .explicit_mpf import (
    ExplicitMPFReference,
    binary_scalar_mpf_rhs,
    double_well_prime,
    explicit_mpf_residual,
    explicit_mpf_rhs,
    load_explicit_mpf_initial_reference,
    periodic_laplacian_2d_channels,
    project_simplex,
)

__all__ = [
    "ScalarAllenCahnConfig",
    "SimulationResult",
    "circular_grain",
    "equivalent_radius",
    "free_energy",
    "load_benchmark_config",
    "periodic_laplacian",
    "planar_slab",
    "scalar_rhs",
    "simulate",
    "MultiphasePFConfig",
    "MultiphaseResult",
    "initial_multiphase_condition",
    "load_multiphase_config",
    "multiphase_free_energy",
    "multiphase_rhs",
    "multigrain",
    "simulate_multiphase",
    "two_grain_circular",
    "ExplicitMPFReference",
    "binary_scalar_mpf_rhs",
    "double_well_prime",
    "explicit_mpf_residual",
    "explicit_mpf_rhs",
    "load_explicit_mpf_initial_reference",
    "periodic_laplacian_2d_channels",
    "project_simplex",
]
